// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjGKg33_RyMlEYTi4bEONVxXmtR7pYdQ',
    appId: '1:305385359708:web:cc13ffe40bb8260f799999',
    messagingSenderId: '305385359708',
    projectId: 'suvhayatra-001',
    authDomain: 'suvhayatra-001.firebaseapp.com',
    databaseURL: 'https://suvhayatra-001-default-rtdb.firebaseio.com',
    storageBucket: 'suvhayatra-001.appspot.com',
    measurementId: 'G-PX2J1VGDPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjGCAkBlGkBNDYKLaM3bi929RjHrTIoI',
    appId: '1:305385359708:android:d8a65cd298b4d05a799999',
    messagingSenderId: '305385359708',
    projectId: 'suvhayatra-001',
    databaseURL: 'https://suvhayatra-001-default-rtdb.firebaseio.com',
    storageBucket: 'suvhayatra-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuAEokB4WtnXhz-q2tNarLOhe42X4LK6o',
    appId: '1:305385359708:ios:18f43ef8835ced76799999',
    messagingSenderId: '305385359708',
    projectId: 'suvhayatra-001',
    databaseURL: 'https://suvhayatra-001-default-rtdb.firebaseio.com',
    storageBucket: 'suvhayatra-001.appspot.com',
    iosBundleId: 'com.example.subhayatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuAEokB4WtnXhz-q2tNarLOhe42X4LK6o',
    appId: '1:305385359708:ios:403317c63c33cc5b799999',
    messagingSenderId: '305385359708',
    projectId: 'suvhayatra-001',
    databaseURL: 'https://suvhayatra-001-default-rtdb.firebaseio.com',
    storageBucket: 'suvhayatra-001.appspot.com',
    iosBundleId: 'com.example.subhayatra.RunnerTests',
  );
}
